### ISSUE TITLE
Fix `src` module name (`src` -> `pythonturtle`)

### ISSUE THREAD

**Issue by bittner** [cool-RR/PythonTurtle#106]
As explained in [PR #105](https://github.com/cool-RR/PythonTurtle/pull/105#pullrequestreview-155871651), the module name of this software is regarded to be `src` from Python's point of view.

It probably makes sense to make it be `pythonturtle` or similar. We shall introduce a standard layout for stand-alone applications (e.g. a `__main__` module in the module root, or so -- see [related StackOverflow answer](https://stackoverflow.com/questions/4042905/what-is-main-py)).

This might also play into packaging a Windows installer (not sure what the current build process for Windows depends on). There was an [interesting talk](https://www.pycon.it/media/conference/slides/pachettizzare-applicazioni-python-in-un-singolo-file-binario.pdf) on the current state of building self-contained installers with Python at this year's Python Italy (FYI, [related question](https://stackoverflow.com/questions/5458048/how-to-make-a-python-script-standalone-executable-to-run-without-any-dependency) on SlackOverflow).

**Comment by cool-RR** [comment]
I looked into the `homedirectory` module. I haven't looked at that code in around a decade so I had no memory of it. It's terrible. There's no reason to do that. There should just be a package `python_turtle` and then relative imports inside of it. Let me know if you need any guidance.

**Comment by bittner** [comment]
> Let me know if you need any guidance.

If you want to tackle that ... that would be cool. :+1:

**Comment by cool-RR** [comment]
I experimented a little with `__main__` now. It's a good idea, but there are a couple of things I don't like:

1. You can't use imports in a sane way from within it. I tried both relative imports and importing the package by name, and neither work. I'm not sure what's the rationale behind this. I looked for a PEP and couldn't find one. 

2. There isn't a Python file you could just put a shebang on and run directly instead of invoking `python pythonturtle`.

So my preference is this: Change the `src` directory to be `python_turtle`, and add a file `run_python_turtle.py` that imports `python_turtle` and runs a function `start()` in it that starts the GUI.

**Comment by cool-RR** [comment]
Okay, so I just loaded PythonTurtle into my IDE after almost a decade of not running it... And now I realize how much work it's going to take to get it running normally. I never tried running it under Python 3. I don't want to spend time on it. I can help you with words but I don't want to be coding.

If you'd like to do a `__main__.py` file despite of my opinion, you can go ahead and do that.

**Comment by bittner** [comment]
Totally fine. :smile: 

At least you can truly appreciate my efforts!  :laughing: 

And yes, `__main__` is awesome! You can run `python -m python_turtle` with it. You can run it as a ZIP file with `python python_turtle.zip`. You can run it as `python python_turtle/`. And it's a natural starting point to jump in when you see a `__main__.py` file in a directory of a Python project.

We'll get the relative efforts fixed in a sane way soon. I'm not a fan of using the full module path, but we'll see. It would have been all easier with zero complaints from`flake8` and `pylint`, but that doesn't look feasible at the moment.

**Comment by bittner** [comment]
... ah, and we'll get a `/usr/local/bin/python_turtle` script (with a shebang line) installed on target systems, so we're all set.  :smiley:

**Comment by cool-RR** [comment]
I did a few more experiments with `__main__.py`. Once you use `python -m python_turtle`, you can import the package by name from `__main__.py`, and then from any package files you can do both relative imports and importing by full name (e.g. `import python_turtle.whatever`)

So I'm happy with using `__main__.py` :)

**Comment by bittner** [comment]
Fixed by PR #115.
