### ISSUE TITLE
Impossible to go back to prompt after entering "help()"

### ISSUE THREAD

**Issue by bittner** [cool-RR/PythonTurtle#113]
When you enter `help()` in the interactive shell you get a screen that looks like this:

```
...

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, or topics, type "modules",
"keywords", or "topics".  Each module also comes with a one-line summary
of what it does; to list the modules whose summaries contain a given word
such as "spam", type "modules spam".

help>
```
From this screen it's impossible to go back to the interactive prompt that allows you to enter commands. You can move the cursor prompt using the mouse, but not using the keyboard's arrows keys. It seems like the key strokes are being captured by the interactive `help>` screen.

It should be possible to exit from this screen, just like it is when using the "real" Python interpreter.

**Comment by cool-RR** [comment]
I would just delete `__builtin__.help`, or change it to a function that
makes the PythonTurtle help show up. It's pretty minor anyway, feel free to
deal with it if you'd like.

**Comment by bittner** [comment]
Similar with `exit()`, by the way. Alright, let's deal with it at due time.

**Comment by bittner** [comment]
Also, `license()` turns out to have the same behavior as `help()`. That needs to be mitigated, too.
