### ISSUE TITLE
Fix remaining Pylint complaints

### ISSUE THREAD

**Issue by bittner** [cool-RR/PythonTurtle#128]
We're currently [ignoring many common style issue](https://github.com/cool-RR/PythonTurtle/blob/master/tox.ini#L49) with Pylint. The remaining ones should be considered serious, and should be fixed.

Reported issues
----------
The output of Pylint is currently: (split up by module)

> [pythonturtle.turtleprocess](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/turtleprocess.py)
```python
pythonturtle/turtleprocess.py:217:-1: W0105: String statement has no effect (pointless-string-statement)
pythonturtle/turtleprocess.py:251:-1: W0105: String statement has no effect (pointless-string-statement)
```
> [pythonturtle.turtlewidget](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/turtlewidget.py)
```python
pythonturtle/turtlewidget.py:28:42: W0511: todo: Change to something smarter? (fixme)
pythonturtle/turtlewidget.py:87:10: W0511: TODO: should make the delay customizable? (fixme)
```
> [pythonturtle.misc.vector](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/misc/vector.py)
```python
pythonturtle/misc/vector.py:54:4: R0201: Method could be a function (no-self-use)
pythonturtle/misc/vector.py:70:-1: W0105: String statement has no effect (pointless-string-statement)
```
> [pythonturtle.shelltoprocess.console](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/shelltoprocess/console.py)
```python
pythonturtle/shelltoprocess/console.py:41:4: W0221: Parameters differ from overridden 'write' method (arguments-differ)
pythonturtle/shelltoprocess/console.py:45:4: R0201: Method could be a function (no-self-use)
pythonturtle/shelltoprocess/console.py:49:4: W0221: Parameters differ from overridden 'push' method (arguments-differ)
pythonturtle/shelltoprocess/console.py:112:4: W0221: Parameters differ from overridden 'interact' method (arguments-differ)
pythonturtle/shelltoprocess/console.py:130:-1: W0105: String statement has no effect (pointless-string-statement)
```
> [pythonturtle.shelltoprocess.shell](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/shelltoprocess/shell.py)
```python
pythonturtle/shelltoprocess/shell.py:24:4: W0221: Parameters differ from overridden 'push' method (arguments-differ)
```
As soon as those are fixed, we can [flip the switch](https://github.com/cool-RR/PythonTurtle/blob/master/.travis.yml#L23) to enforce code quality.

Related (reading material)
--------

- [flake8](http://flake8.pycqa.org/) (official docs)
- [Pylint](https://www.pylint.org/) (official docs)
- [Black](https://black.readthedocs.io/) (official docs)
- [Consistent Python code with Black](https://www.mattlayman.com/blog/2018/python-code-black/) (blog)

**Comment by bittner** [comment]
Could you try to fix those issues? You know the code best.

That would really help. :+1:

**Comment by cool-RR** [comment]
I think that PyLint is okay now. I tried checking, saw there were errors, but then saw it was flake8! I guess you're using both? Let me know whether pylint is passing, and how to add ignores to flake8. (I'm not a fan of linting, so anything that isn't an obvious error I'd prefer to add to the ignore list.)

**Comment by bittner** [comment]
Yes! Now Pylint is happy and flake8 complains (for a reason). :smile: 

You can simply run `tox` locally to see whether all checks and tests pass, before pushing the changes. Or single checks (flake8, Pylint, etc.) only via `tox -e flake8,pylint`.

Flake8 is [complaining about](https://travis-ci.org/cool-RR/PythonTurtle/jobs/437940589#L492) the commenting style:
```python
./pythonturtle/turtleprocess.py:246:13: E116 unexpected indentation (comment)
./pythonturtle/turtleprocess.py:247:17: E116 unexpected indentation (comment)
```
The commenting character should be aligned vertically. ([see code](https://github.com/cool-RR/PythonTurtle/commit/66d12e891ddf72d4929713f702b94fc976ef423f#diff-a1023274963ded4c308b10d4248c1f68R246))
```python
./pythonturtle/shelltoprocess/console.py:122:16: E114 indentation is not a multiple of four (comment)
./pythonturtle/shelltoprocess/console.py:122:16: E116 unexpected indentation (comment)
./pythonturtle/shelltoprocess/console.py:125:24: E114 indentation is not a multiple of four (comment)
./pythonturtle/shelltoprocess/console.py:125:24: E116 unexpected indentation (comment)
./pythonturtle/shelltoprocess/console.py:126:25: E116 unexpected indentation (comment)
```
Same here. Simply try to vertically align the `#` character across the whole code block. ([see code](https://github.com/cool-RR/PythonTurtle/commit/66d12e891ddf72d4929713f702b94fc976ef423f#diff-b44eabd35f44f19247de17113c7e5306R126))

**Comment by cool-RR** [comment]
That's the way my IDE comments multiple lines when I press the hotkey. I don't agree that aligning the hashes vertically is important. I mean, it's not a hassle to fix these instances, I just don't want to have to think about it every time I comment code.

**Comment by bittner** [comment]
At the end, you could activate the enforcement of code quality with two simple measures:

1. Remove [the line that allows](https://github.com/cool-RR/PythonTurtle/blob/master/.travis.yml#L25) the Pylint check to fail in the Travis configuration (`.travis.yml`, line 25)
1. Protect the default branch (`master`) by adding a Branch Protection Rule in the [branches settings](https://github.com/cool-RR/PythonTurtle/settings/branches); check "Require status checks to pass before merging" and maybe also "Require branches to be up to date before merging" [in the new rule](https://github.com/cool-RR/PythonTurtle/settings/branch_protection_rules/new) to require tests to pass before anything can be merged into `master`.

Optionally, uncheck "Allow merge commits" and "Allow squash merging" in the [Merge button](https://github.com/cool-RR/PythonTurtle/settings) section of the GitHub project settings; this makes the commit history linear (by avoiding merge commits), which is nicer to read. -- (I like that!)

I reopen this issue to make it easier to track for us.

**Comment by cool-RR** [comment]
I didn't understand at all how your comment is related to the discussion.

**Comment by bittner** [comment]
> I don't agree that aligning the hashes vertically is important.

I agree with you that it's "not important" (technically). But we're pythonistas, and pythonistas love to follow [PEP 20](https://www.python.org/dev/peps/pep-0020/):

> Beautiful is better than ugly.

... and flake8 simply reminds us about that.

**Comment by bittner** [comment]
> I didn't understand at all how your comment is related to the discussion.

You mean, the comment about enforcing code quality?

Flake8 and Pylint enforce code quality in combination with the repository settings I explained. We make sure by this that the default branch stays clean (stays the same or only gets cleaner by each and every commit).

**Comment by cool-RR** [comment]
I don't always agree with PEP 20. I have no issue with flake8 giving errors
as long as it doesn't block anything.

**Comment by bittner** [comment]
> as long as it doesn't block anything

The whole point about QA tools, in the end, is blocking us to make code worse.

**Comment by bittner** [comment]
It's really easy now, that we soooo close to having a completely green buld! We just need to flip the switches, address the two minor things from above, _and we're there!_ -- Isn't that awesome?

**Comment by cool-RR** [comment]
> The whole point about QA tools, in the end, is blocking us to make code worse.

Except everyone has a different idea of what it means to "make code worse".

I don't think that all of the rules enforced by pylint and flake8 are important enough to block code. It's funny, the PythonTurtle code that I wrote a decade ago is shitty. If I wrote it again today, I'd write it differently. No PyLint or flake8 would ever complain about the shitty structure of the code, because they don't care. They're good as automatic tools to catch a few errors.

> It's really easy now, that we soooo close to having a completely green buld!

We don't work for the green build, the green build works for us. 

I'll fix the comment thing manually since I see that you care a lot about that.

**Comment by bittner** [comment]
> Except everyone has a different idea of what it means to "make code worse".

Granted. The tools give us feedback, though.

- Flake8 puts a heavy focus on style (i.e. PEP 20), that leaves more room for interpretation.
- Pylint, on the other hand, [does more than just static code analysis](https://www.pylint.org/), hence can detect modules we forgot to install or import. It's _really, really_ helpful once you get used to it!

> I'll fix the comment thing manually since I see that you care a lot about that.

It's not really (just) about me. And it's not (just) about the comments. You'll understand later. -- I always have these kind of discussions in the beginning of a QA process, and even at conference talks. It's a normal thing to be suspicious.

> We don't work for the green build, the green build works for us.

Exactly! Now we need to configure GitHub and Travis to make the green build work for us. --> When it's green it should allow changes to go into the main line, when red not. That's the whole story about [CI and CD](https://painless.software/continuous-integration).

**Comment by cool-RR** [comment]
Okay, so regarding your instructions above "At the end", you'll do the first part and I'll do the rest? Let me know when you want me to.

**Comment by bittner** [comment]
Well, "the first part" is just remove one line of code. Anyone can do that! :smiley: Do you care that I do it?

**Comment by bittner** [comment]
... you can make a feature branch and open a PR, if you want me to review the changes. :100:

**Comment by cool-RR** [comment]
Okay, I did your instructions, even though I was able to push "Test commit 3" and its friends, not sure how push worked given that it didn't have time to run the build before accepting the push.

**Comment by bittner** [comment]
Maybe that's related to the fact that you're the owner of the repository project. There's an option saying something with "Administrator" in the push rule. Maybe you want to play with that.

**Comment by cool-RR** [comment]
That was before I disabled pushing to master, we're good now
