### ISSUE TITLE
Make shell not ignore text typed when process is busy

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#24]

**Comment by bittner** [comment]
Oh yeah, this is a huge topic! -->

If in any way possible, it should be possible to interrupt the calculations (e.g. by pressing `<Ctrl>`+`C`). When there is a long range, or a tedious nested loop, there's currently no way to interrupt the turtle, and return to the interpreter prompt. :worried:

**Comment by cool-RR** [comment]
Yep, this is definitely an issue. Don't we have a ticket for that? If you
don't see one free to create one. I think that multiple people asked me
about that.

**Comment by bittner** [comment]
Closing this issue in favor of #126.
