### ISSUE TITLE
make it possible to copy&paste from help?

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#30]
Email:

Greetings,

 Please make it possible to copy the example coding and change and execute

Cheers, Kishore.

**Comment by bittner** [comment]
If someone ever suggests implementing the help pages in HTML (being rendered; something like https://github.com/cool-RR/PythonTurtle/issues/65#issuecomment-436578) it should be taken into consideration that selection of text, and copy+paste, is not available.

The current look and feel, user experience, should stay for the sake of learning to _type_ the commands needed to get Python programs working.

**Comment by cool-RR** [comment]
Agreed.

**Comment by bittner** [comment]
We may mention this in some kind of documentation or somewhere in the application where users notice it. :+1:
