### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#36]
I _may_ get roasted for this comment, but i think a turtle module
along the lines of what you have here would better serve the stdlib.
The current implementation is great, but the whole purpose of turtle
is to help children or non-programmers get a feel of the language in a
very, very, simple and fun way. Your app is presented in much the same
way as any over-the-counter windows app any non-programmer has seen
before making them _feel_ a little more comfortable.

[warning wild speculations ahead!!]
I just guessing here, but i'll bet many of these _noobs_ have found
the current turtle just a wee-bit more advanced than they can handle,
and _some_ have been scared off. I would also venture to say a key-map
of sorts that is available thru the help menu where one could push an
"Up" button, or a "rotate" button, and have the proper command
inserted in the prompt, and then have the command execute, may also
help make the connections here, a sort of _real_ Visual Basic
programming -- sorry Microsoft :P

**Comment by bittner** [comment]
Closing this issue as going away from typing Python code is clearly not the idea of PythonTurtle.

For "don't let copy+paste" sneak in there's issue #30.
