### ISSUE TITLE
delete installer files from old commits in the repo, they're too heavy

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#6]

**Comment by bittner** [comment]
This has been done with commits 093a521 and 0adeb34. :heavy_check_mark: 

Maybe there is some way to "compact" the repository, to avoid having to download a huge, unnecessary history? Maybe this? --> :man_shrugging: 

- [Compact Git repository with history depth](https://stackoverflow.com/questions/31785389/compact-git-repository-with-history-depth) (StackOverflow)
- [How to Shrink a Git Repository](http://stevelorek.com/how-to-shrink-a-git-repository.html) (Steve Lorek)
- [Compact repo by removing old commits](https://stackoverflow.com/questions/16854425/compact-repo-by-removing-old-commits) (StackOverflow)
- [Reduce git repository size](https://stackoverflow.com/questions/2116778/reduce-git-repository-size) (StackOverflow)
- [Maintenance and Data Recovery - Git Internals](https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery) (official Git documentation)

**Comment by cool-RR** [comment]
Care to copy paste that information to a new ticket?
