### ISSUE TITLE
Which version of Python to package with?

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#84]
I see that in one of the installers you created you packaged PythonTurtle with Python 2.7.

We need to think whether this is wise. I guess we have two sensible choices: Python 2.6 or Python 2.7.

Now, Python 2.7 is definitely more awesome than Python 2.6. (I <3 dict comprehensions.) And it's closer to Python 3.x which is the future. But it's still not the present... Python 2.7 is barely used in production settings as far as I know, and I would hate to teach people Python 2.7 only to tell them later, "You see these cool dict comprehensions? You won't be able to use them for a few years." Now it's true that by the time the kid grows up Python 3.x will probably kick in, but still I'd like to know that we're teaching something that is actually being used **right now** in the real world.

Therefore I prefer to package PythonTurtle with Python 2.6.

**Comment by bittner** [comment]
Can we close this issue?
