### ISSUE TITLE
Running pythonturtle.py but returning "undefined symbol PyUnicodeUCS2_FromEncodedObject" error

### ISSUE THREAD

**Issue by CC-Hsu** [cool-RR/PythonTurtle#97]
Hi,

I try to run PythonTurtle from source with python2, OS Slackware 14.2.

But I get a wxPython error "undefined symbol PyUnicodeUCS2_FromEncodedObject".

After search it around, it seems that I need to run PythonTurtle in a Python built with "--enable-unicode=ucs2" option.

The Python package I used now is compiled with "--enable-unicode=ucs4" option (Official build from Slackware).

I don't want to build one more python by myself.

Is it possible to remove restriction on unicode support in PythonTurtle?

Thanks.

**Comment by cool-RR** [comment]
Thanks for reporting, but I haven't been actively working on PythonTurtle
for around 7 years so I'm not likely to fix this bug.

**Comment by CC-Hsu** [comment]
Hi,

Thanks for your reply.

I check the problem again and find that its my wxPython installation problem.

So I will keep on trying to make PythonTurtle work.
